### ISSUE TITLE
Self defined foreign keys

### ISSUE THREAD

**Issue by vkorobkov** [rodionovsasha/jfixtures#111]
Probably for small project or database it would be useful to define foreign keys on the place:

Short(or relative) table name:
```yml
vlads_comment:
  text: Hello
  # users table should be looked up first in the same directory as current fixture is
  # otherwise the general lookup strategy from fixtures root folder should be user
  user_id: users:vlad # trying to find users table and vlad in it
```

Table name with schema:
```yml
vlads_comment:
  text: Hello
  # the same lookup strategy as above: relative first, canonical after 
  user_id: public.users:vlad # trying to find public.users table and vlad in it
```

Foreign key to any field other than to PK:
```yml
vlads_comment:
  text: Hello
  user_id: public.users:vlad:public_id # refers to public_id column of public.users table
```

Table relations defined in `.conf.yml` would be the default behaviour, but manually defined FKs would override it.
