### ISSUE TITLE
Have a mechanism to define tables order AND is different that relationships

### ISSUE THREAD

**Issue by vkorobkov** [rodionovsasha/jfixtures#112]
Currently the order tables go to the destination SQL is not defined except one rule: referred tables go strictly before the referring ones.

However, except the relationship, there might be other cases when the tables order is important: table can have dependencies on triggers/stored procedures/default  values level.

So there should be a way to say that table `A` goes before table `B` and these rules should have the highest priority, higher, than table ordering defined by relationships. The circular references should still be detected in the same manner.

A possible format of describing such dependencies in `.conf`:
```yaml
# maybe a new <requires> table property
user_needs_roles:
  apply_to: users
  requires: [roles, permissions] # the required tables go before <users>
```
