### ISSUE TITLE
Support yaml anchors in fixtures

### ISSUE THREAD

**Issue by vkorobkov** [rodionovsasha/jfixtures#123]
YAML [has a concept of "anchors"](https://learnxinyminutes.com/docs/yaml/):
```yaml
# Anchors can be used to duplicate/inherit properties
base: &base
    name: Everyone has same name

foo: &foo
    <<: *base
    age: 10

bar: &bar
    <<: *base
    age: 20
```

Though defining an anchor counts as another separate when we read YAML and anchors go to SQL as a separate SQL rows.

It needs to have a way of _not including_ anchors into the SQL and using them only for inheritance. For example, anchored rows may have a dot(`.`) prefix, which mean we do not include them into the SQL:
```yaml
# Anchors can be used to duplicate/inherit properties
".base": &base
    name: Everyone has same name

foo: &foo
    <<: *base
    age: 10

bar: &bar
    <<: *base
    age: 20
```

These WIKI pages should be updated correspondingly: [default columns](https://github.com/vkorobkov/jfixtures/wiki/Default-columns), [fixture](https://github.com/vkorobkov/jfixtures/wiki/Fixture)
